name: Deploy On server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: cd ~/vault && git pull "https://Cameron-Ross:$PASSWORD@github.com/4800CodeCrushers/vault.git" && sudo service apache2 restart