name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Dump key
        id: setup-key
        env:
            PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          echo "$PRIVATE_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
      
      - name: Update app on server
        env:
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}
        run: ssh -i $HOME/key.pem -o StrictHostKeyChecking=no ${USER_NAME}@${HOSTNAME} 'update'